env:
  browser: true
  node: true
  es6: true
extends: ['eslint:recommended', "plugin:react/recommended", "prettier"]
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  react/prop-types: 
    - 0
  semi:
    - error
    - never
  no-undef:
    - error
globals: 
  module: true
  